{
  "GenericSwapFacetV3": {
    "arbitrum": {
      "production": [
        {
          "TIMESTAMP": "2025-07-08 11:56:21",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:12:34",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:16:22",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:18:48",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:25:47",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:31:59",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:35:30",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:37:55",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        },
        {
          "TIMESTAMP": "2025-07-08 12:39:49",
          "ERROR_MESSAGE": "UnknownDaggerError: Encountered an unknown error while requesting data via graphql\nStack: UnknownDaggerError: Encountered an unknown error while requesting data via graphql\n    at new DaggerSDKError (/src/.dagger/sdk/core.js:61780:7)\n    at new UnknownDaggerError (/src/.dagger/sdk/core.js:61820:7)\n    at <anonymous> (/src/.dagger/sdk/core.js:86274:15)\n    at processTicksAndRejections (native:7:39)",
          "ENVIRONMENT": "production"
        }
      ]
    }
  }
}